name: Checkov

on:
  pull_request:

jobs:
  checkov:
    name: Checkov Policy Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install deps
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install checkov
        run: pip install checkov

      - name: Check blps
        run: checkov -d .
